version: "3"
services:
   web:
     image: php:v2
     ports:
     - "81:80"
     depends_on:
     - mysql
   mysql:
     image: db:v2
     volumes:
     - db_data:/var/lib/mysql
     environment:
        MYSQL_DATABASE: mydatabase
        MYSQL_ROOT_PASSWORD: password
volumes:
   db_data: {}